[DET-001 Suspicious PowerShell]
search = index=pwsh EventCode=4104 | search Message="*EncodedCommand*" OR Message="*-enc*" OR Message="*Invoke-Expression*" OR Message="*DownloadString*" OR Message="*Hello, from PowerShell*"
disabled = 0
is_scheduled = 1
cron_schedule = 0 * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
action.email = 0

[DET-002 LSASS Process Access]
search = index=sysmon host=WS01 earliest=-24h (procdump OR lsass OR TargetImage="*lsass.exe*")
disabled = 0
is_scheduled = 1
cron_schedule = 0 * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
action.email = 0

[DET-003 Kerberoasting Activity]
search = index=win EventCode=4769 earliest=-24h (svc_sql OR MSSQLSvc)
disabled = 0
is_scheduled = 1
cron_schedule = 0 * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
action.email = 0

[DET-004 Scheduled Task Persistence]
search = index=win earliest=-24h (EventCode=4698 OR EventCode=4702) OR (index=sysmon earliest=-24h (schtasks OR "Schedule.Service" OR "scheduled task"))
disabled = 0
is_scheduled = 1
cron_schedule = 0 * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
action.email = 0

[DET-005 Security Log Cleared]
search = (index=win EventCode=1102 earliest=-24h) OR (index=sysmon earliest=-24h (wevtutil OR Clear-EventLog OR "cl Security"))
disabled = 0
is_scheduled = 1
cron_schedule = 0 * * * *
alert_type = number of events
alert_comparator = greater than
alert_threshold = 0
action.email = 0
