[WinEventLog://Security]
disabled = 0
index = win
renderXml = false

[WinEventLog://System]
disabled = 0
index = win

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = sysmon
renderXml = true

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = pwsh
